# Generated by Django 3.2.8 on 2021-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Book Name')),
                ('picture', models.ImageField(upload_to='blog_image', verbose_name='Book Image')),
                ('author', models.CharField(max_length=264, verbose_name="Author's Name")),
                ('email', models.EmailField(blank=True, max_length=264)),
                ('describe', models.TextField(verbose_name='Add a short description')),
            ],
        ),
    ]
