# Generated by Django 3.2.8 on 2021-10-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_books_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=264, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.ImageField(upload_to='book_image'),
        ),
    ]
